### ISSUE TITLE
[Kubernetes on CoreOS with flannel] Cannot start kubedash 

### ISSUE THREAD

**Issue by ltagliamonte** [kubernetes/kubedash#36]
I have a brand new installation of Kubernetes on CoreOs with flannel, i'd like to try kubedash I created the Heapster rc and service, but when I try to run in a pod or on local master docker the afein/kubedash i got the following error:
```
I0903 14:28:42.422511       1 kubedash.go:82] /kubedash
I0903 14:28:42.422543       1 kubedash.go:83] Kubedash version 0.0.1
I0903 14:28:42.422548       1 kubedash.go:84] Starting kubedash on port 8289
E0903 14:28:42.422574       1 helper.go:251] expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
F0903 14:28:42.427178       1 kubedash.go:49] unable to locate Heapster service: monitoring-heapster
```

here my confi files: 
heapster-rc.json
```
{
    "apiVersion": "v1",
    "kind": "ReplicationController",
    "metadata": {
	"labels": {
	    "name": "heapster"
	},
	"name": "monitoring-heapster"
    },
    "spec": {
	"replicas": 1,
	"selector": {
	    "name": "heapster"
	},
	"template": {
	    "metadata": {
		"labels": {
		    "name": "heapster"
		}
	    },
	    "spec": {
		"containers": [
		    {
			"image": "afein/heapster:latest",
			"name": "heapster",
			"command": [
			    "/heapster",
			    "--source=kubernetes:''",
				"--use_model=true",
				"--model_resolution=1m",
				"--cache_duration=4m",
				"--poll_duration=30s",
				"--stats_resolution=10s"
			]
		    }
		]
	    }
	}
    }
}
```
heapster-service.json
```
{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "labels": {
      "kubernetes.io/cluster-service": "true",
      "name": "monitoring-heapster"
    },
    "name": "monitoring-heapster"
  },
  "spec": {
    "ports": [
      {
        "port": 80,
        "targetPort": 8082
      }
    ],
    "selector": {
      "name": "heapster"
    }
  }
}
```
kubedash-pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: kubedash
  labels: 
    name: kubedash
spec: 
  containers: 
    - name: kubedash
      image: afein/kubedash:latest
      ports: 
        - containerPort: 80
          hostPort: 80
          name: kubedash
```
